name: Java Maven Build & publish Artifacts

on:
  push:
    branches: ["main"]
  release:
    types: [published]
  deployment:
    types: [created]

jobs:
  build_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build maven
        run: mvn -B package --file pom.xml



  publish:
    runs-on: ubuntu-latest
    needs: build_tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging